name: suikouji
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  animations: ^2.0.11
  connectivity_plus: ^7.0.0
  crypto: ^3.0.3
  csv: ^6.0.0
  dio: ^5.9.1
  flutter_secure_storage: ^9.2.2
  drift: ^2.31.0
  excel: ^4.0.6
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^20.1.0
  flutter_riverpod: ^3.2.1
  flutter_slidable: ^4.0.3
  riverpod: ^3.2.1
  go_router: ^17.1.0
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  riverpod_annotation: ^4.0.2
  share_plus: ^10.1.4
  shared_preferences: ^2.5.4
  shimmer: ^3.0.0
  sqlite3_flutter_libs: 0.5.30
  uuid: ^4.5.2
  web_socket_channel: ^3.0.2

  clock: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.11.1
  drift_dev: ^2.31.0
  riverpod_generator: ^4.0.3
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

  fake_async: any
flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/splash/

flutter_launcher_icons:
  image_path: assets/icon/app_icon.png
  android: true
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: "#009688"
  image: assets/splash/logo.png
  android: true
  ios: true
  android_12:
    image: assets/splash/logo.png
    color: "#009688"
  fullscreen: true
