name: suikouji
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  animations: ^2.0.11
  audio_session: ^0.2.2
  connectivity_plus: ^7.0.0
  csv: ^6.0.0
  dio: ^5.9.1
  drift: ^2.31.0
  excel: ^4.0.6
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^20.1.0
  flutter_tts: ^4.2.0
  flutter_riverpod: ^3.2.1
  riverpod: ^3.2.1
  go_router: ^17.1.0
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  record: ^6.2.0
  riverpod_annotation: ^4.0.2
  share_plus: ^10.1.4
  shared_preferences: ^2.5.4
  shimmer: ^3.0.0
  sqlite3_flutter_libs: 0.5.30
  uuid: ^4.5.2
  vad: ^0.0.7+1
  web_socket_channel: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.11.1
  drift_dev: ^2.31.0
  riverpod_generator: ^4.0.3

  fake_async: any
flutter:
  uses-material-design: true
